development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: redis

production:
  adapter: redis
  url: redis://:pdae2aeb7c94a9009a407d1c327c72ce818f2f025bc902456d45fc06aa209b60d@ec2-52-5-54-55.compute-1.amazonaws.com:14779
  channel_prefix: devise_production
